### ISSUE TITLE
Cooperation on other app

### ISSUE THREAD

**Issue by niccokunzmann** [falling-fruit/falling-fruit-mobile#34]
Hi Falling Fruit Team,

I am writing an app and hope to get all plant maps on board.
Features: 
- Publishing to multiple APIs (Mundraub, na-ovoce)
- Mapping Categories
- Offline mode with downloaded markers and Fruit Radar notifications

https://github.com/niccokunzmann/mundraub-android

I would like to incorporate Falling Fruit markers. Also publishing if the API is documented (should take me a day or two then).

I could not find your API documentation. **Do you have an API documentation?**
- https://falling-fruit.github.io/api-docs/#tag/clusters%2Fpaths%2F~1clusters~1cluster%2Fget does not tell me about markers
- https://falling-fruit.github.io/api-docs/swagger-ui/ tells me "Can't read from server. It may not have the appropriate access-control-origin settings."

I can read your source code. A documentation like [na-ovoce](https://github.com/jsmesami/naovoce/blob/master/API.apib) was really great.

**How would you like to cooperate?**

**Comment by ezwelty** [comment]
Hi @niccokunzmann,

It is an honorable goal to to interface with all the major fruit maps (and put up with our changes and differences in design)! And I like your focus on offline functionality – that's been on our todo but not yet made it to the top. I would be curious to hear – as a way to better understand where you are coming from – your reasons for choosing to write a new app from scratch rather than working from an existing app like ours or Na-Ovoce's. And your long-term vision for the project (in particular in regards to commercialization or not).

In regards to Falling Fruit, you are catching us in a time of transition. After being distracted by a PhD these last couple years, I will be back to working more actively on Falling Fruit this winter. Until then, API documentation is slim.

+ Code for the live API: https://github.com/falling-fruit/falling-fruit/tree/master/api
+ API build instructions: https://github.com/falling-fruit/falling-fruit#build-instructions-api
+ Incomplete and out of date documentation: https://docs.google.com/document/d/1YMA_d6dT0IZjrJuN5ndz7jzrpSiuwFEsnGcqp9gKgo8/edit#heading=h.5nyzz0mnyjac

What you found (https://github.com/falling-fruit/api-docs) is the draft API documentation, which will be a priority for me to complete once time frees up. As well as a rewrite and design cleanup of the API (https://github.com/falling-fruit/api).

I will be in Berlin to visit Mundraub next month. Maybe we can also meet. More on that in an email.

**Comment by niccokunzmann** [comment]
> I would be curious to hear – as a way to better understand where you are coming from – your reasons for choosing to write a new app from scratch rather than working from an existing app like ours or Na-Ovoce's.

So, the reason for that is manifold:
1. I wrote to Mundraub two years ago about an app and I did not get an answer to all my questions. Two years later there was still no Android app. The platform is not open-source. Communication was not that good. I did not even know that there are other platforms like this around the world. Even if there were, I did not know of an Android app and then one where I can walk through the Alps without Internet connection.
2. I decided to write an App since I had time and I will need Android development knowledge for another project.
3. A positive side for starting yourself is that there is a solution in range. A negative side is that of getting help/a community. I hope to get grip in Mundraub and people using the app, so that I do not have to do that work. It is a hammer-nail understanding: I can program so the solution looks like this. 
4. This is my first Android app and I am not sure if any contributions to existing apps would be accepted. Also, I understand code by writing it. I did not know other platforms/other open-source apps (Na-ovoce is proprietary) and even if I would, I fear not to get the mentoring I need to get started with Android.
5. These fruit sites are sharing platforms that can not be shared. Choose one: Propriatary/undocumented/open-source but not standardized. With this app now, my focus is to show an example that interoperability is achievable and desirable while also solving my use-case of offline walking around and mapping edible plants.

As of (5), I would like to talk to you - if you are interested - about your API - I know what the app needs, I implemented different APIs of fruit sharing platforms. If possible, we can make this API usable and documented in a way that Mundraub/other platforms also provide it in the future.

**Comment by ezwelty** [comment]
@niccokunzmann Thank you very much for explaining your motivations and the context in which you are working. In regards to (5), you have some valuable experience and I would be very happy to talk to you so that I can learn from your experience as I set out to design and document the next version of the Falling Fruit API. Will follow up by email to find a time to chat.

**Comment by niccokunzmann** [comment]
I have time on weekdays probably - because of the time zone difference
almost from your morning on. You can reply to the mail.

**Comment by ezwelty** [comment]
For the record, a documented and more full-featured API for Falling Fruit is now in development (and live in test production) here: https://github.com/falling-fruit/falling-fruit-api

Since https://github.com/niccokunzmann/mundraub-android is no longer actively maintained, I am closing this issue, but feel free to reopen or to start a new issue (perhaps on the API repo) if someone is motivated to add Falling Fruit support.
